import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useSearchParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Check, MapPin, PackageOpen, Phone, Plus, Send, User, Wrench, X } from 'lucide-react'
import { PageTransition } from '../components/shared/PageTransition'
import { SkeletonGrid } from '../components/shared/SkeletonCard'
import { useAuth } from '../context/AuthContext'
import { browseEquipment, createEquipmentListing, getMyListings, getMyRequestsSent, requestEquipment, reviewEquipmentRequest, type EquipmentListing, type EquipmentRequest, type EquipmentType, type RequestPayload, type SentEquipmentRequest } from '../api/equipment'

const types: EquipmentType[] = ['tiller', 'sprayer', 'harvester', 'water_pump', 'other']
const ago = (value: string) => { const m = Math.max(1, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return m < 60 ? `${m}m ago` : m < 1440 ? `${Math.floor(m / 60)}h ago` : `${Math.floor(m / 1440)}d ago` }
const statusStyle = (status: string) => status === 'accepted' || status === 'available' ? 'badge-green' : status === 'rejected' || status === 'booked' ? 'badge-red' : 'badge-amber'

export const EquipmentSharing = () => {
  const { t } = useTranslation(); const { user } = useAuth(); const client = useQueryClient(); const [params, setParams] = useSearchParams()
  const [tab, setTab] = useState<'browse' | 'listings' | 'requests'>(params.get('tab') === 'listings' ? 'listings' : params.get('tab') === 'requests' ? 'requests' : 'browse')
  const [type, setType] = useState<EquipmentType | ''>(''); const [location, setLocation] = useState(''); const [notice, setNotice] = useState(''); const [requesting, setRequesting] = useState<EquipmentListing | null>(null); const [addOpen, setAddOpen] = useState(false); const [glowing, setGlowing] = useState<Set<string>>(new Set()); const [requestedIds, setRequestedIds] = useState<Set<string>>(new Set())
  const [requestForm, setRequestForm] = useState<RequestPayload>({ requester_name: user?.name || '', requester_address: '', requester_contact_number: '', message: '' })
  const [listingForm, setListingForm] = useState({ equipment_name: '', equipment_type: 'tiller' as EquipmentType, description: '', location: '', contact_number: '' })
  const filters = useMemo(() => ({ ...(type ? { equipment_type: type } : {}), ...(location ? { location } : {}) }), [type, location])
  const browse = useQuery({ queryKey: ['equipment', 'browse', filters], queryFn: () => browseEquipment(filters) })
  const listings = useQuery({ queryKey: ['equipment', 'mine'], queryFn: getMyListings, enabled: tab === 'listings', refetchInterval: tab === 'listings' ? 9000 : false })
  const sent = useQuery({ queryKey: ['equipment', 'sent'], queryFn: getMyRequestsSent, enabled: tab === 'requests', refetchInterval: tab === 'requests' ? 9000 : false })
  const priorRequests = useRef<Map<string, string> | null>(null); const priorSent = useRef<Map<string, string> | null>(null)
  useEffect(() => { setTab(params.get('tab') === 'listings' ? 'listings' : params.get('tab') === 'requests' ? 'requests' : 'browse') }, [params])
  useEffect(() => { if (!listings.data) return; const current = new Map<string, { request: EquipmentRequest; listing: EquipmentListing }>(); listings.data.forEach(listing => listing.requests.forEach(request => current.set(request.request_id, { request, listing }))); if (priorRequests.current) current.forEach(({ request, listing }, id) => { if (!priorRequests.current!.has(id) && request.status === 'pending') { setNotice(`New request from ${request.requester_name} for ${listing.equipment_name}.`); setGlowing(old => new Set(old).add(listing._id)) } }); priorRequests.current = new Map([...current].map(([id, value]) => [id, value.request.status])) }, [listings.data])
  useEffect(() => { if (!sent.data) return; const current = new Map(sent.data.map(item => [item.request.request_id, item])); if (priorSent.current) current.forEach((item, id) => { const previous = priorSent.current!.get(id); if (previous === 'pending' && item.request.status !== 'pending') { setGlowing(old => new Set(old).add(item.request.request_id)); setNotice(item.request.status === 'accepted' ? `${item.listing.owner_name} accepted your request for ${item.listing.equipment_name}! Contact: ${item.listing.contact_number}` : `${item.listing.owner_name} is unable to lend ${item.listing.equipment_name} right now.`) } }); priorSent.current = new Map([...current].map(([id, item]) => [id, item.request.status])) }, [sent.data])
  const invalidate = () => client.invalidateQueries({ queryKey: ['equipment'] })
  const sendRequest = useMutation({ mutationFn: requestEquipment, onSuccess: () => { if (requesting) setRequestedIds(ids => new Set(ids).add(requesting._id)); setNotice(`Request sent to ${requesting?.owner_name || 'owner'}`); setRequesting(null); client.invalidateQueries({ queryKey: ['equipment', 'sent'] }) }, onError: error => setNotice(error.message) })
  const review = useMutation({ mutationFn: reviewEquipmentRequest, onMutate: async ({ listingId, requestId, action }) => { await client.cancelQueries({ queryKey: ['equipment', 'mine'] }); const previous = client.getQueryData<EquipmentListing[]>(['equipment', 'mine']); client.setQueryData<EquipmentListing[]>(['equipment', 'mine'], data => data?.map(listing => listing._id !== listingId ? listing : { ...listing, availability_status: action === 'accept' ? 'booked' : listing.requests.filter(r => r.request_id !== requestId).every(r => r.status !== 'pending') ? 'available' : 'requested', requests: listing.requests.map(r => r.request_id === requestId ? { ...r, status: action === 'accept' ? 'accepted' : 'rejected' } : action === 'accept' && r.status === 'pending' ? { ...r, status: 'rejected' } : r) })); return { previous } }, onError: (_error, _value, context) => { if (context?.previous) client.setQueryData(['equipment', 'mine'], context.previous); setNotice('Unable to update request. Please try again.') }, onSuccess: invalidate })
  const add = useMutation({ mutationFn: createEquipmentListing, onSuccess: () => { setAddOpen(false); setNotice('Equipment listing created.'); invalidate(); setTab('listings'); setParams({ tab: 'listings' }) } })
  const selectTab = (next: typeof tab) => { setTab(next); setParams(next === 'browse' ? {} : { tab: next }) }
  const submitRequest = (event: FormEvent) => { event.preventDefault(); if (!requesting || !requestForm.requester_name.trim() || !requestForm.requester_address.trim() || !/^\+?[0-9\s-]{7,25}$/.test(requestForm.requester_contact_number)) return setNotice('Please complete the required request details with a valid contact number.'); sendRequest.mutate({ id: requesting._id, data: requestForm }) }
  const submitListing = (event: FormEvent) => { event.preventDefault(); if (!listingForm.equipment_name || !listingForm.description || !listingForm.location || !/^\+?[0-9\s-]{7,25}$/.test(listingForm.contact_number)) return setNotice('Please complete all listing fields with a valid contact number.'); add.mutate(listingForm) }
  return <PageTransition><main className="page-content" style={{ maxWidth: 1200, margin: '0 auto', padding: '36px 24px 80px' }}>
    <section className="card" style={{ padding: '28px 32px', marginBottom: 24, background: 'linear-gradient(135deg, #E8F5E9, #F4FBF5)' }}><h1 style={{ margin: 0, fontFamily: 'Poppins, sans-serif', color: 'var(--color-primary)' }}>{t('equipment_title')}</h1><p style={{ margin: '7px 0 0', color: 'var(--color-text-secondary)' }}>{t('equipment_desc')}</p></section>
    <div className="tab-bar" style={{ marginBottom: 20, width: 'fit-content' }}>{(['browse', 'listings', 'requests'] as const).map(item => <button key={item} className={`tab-item ${tab === item ? 'active' : ''}`} onClick={() => selectTab(item)}>{tab === item && <motion.span layoutId="equipment-tab" style={{ position: 'absolute', inset: 0, borderRadius: 9, background: 'var(--color-primary)', zIndex: -1 }} />}{item === 'requests' ? 'My Requests' : t(`equipment_tab_${item}`)}</button>)}</div>
    <AnimatePresence>{notice && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} onAnimationComplete={() => setTimeout(() => setNotice(''), 4000)} style={{ padding: 11, marginBottom: 16, borderRadius: 10, background: '#E8F5E9', color: '#1B5E20', fontWeight: 600 }}>{notice}</motion.div>}</AnimatePresence>
    {tab === 'browse' && <><div className="card" style={{ padding: 16, marginBottom: 20, display: 'flex', gap: 12, flexWrap: 'wrap' }}><select className="form-select" value={type} onChange={e => setType(e.target.value as EquipmentType | '')} style={{ maxWidth: 230 }}><option value="">{t('equipment_all_types')}</option>{types.map(x => <option key={x} value={x}>{t(`equipment_type_${x}`)}</option>)}</select><input className="form-input" value={location} onChange={e => setLocation(e.target.value)} placeholder={t('equipment_search_location')} style={{ flex: 1 }} /></div><ListingGrid loading={browse.isLoading} listings={browse.data} requestedIds={requestedIds} onRequest={listing => { setRequestForm(x => ({ ...x, requester_name: user?.name || x.requester_name })); setRequesting(listing) }} /></>}
    {tab === 'listings' && <><button className="btn btn-primary" onClick={() => setAddOpen(true)} style={{ marginBottom: 20, display: 'inline-flex', gap: 8 }}><Plus size={17} />{t('equipment_add_listing')}</button>{listings.isLoading ? <SkeletonGrid /> : listings.data?.length ? <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(290px, 1fr))', gap: 18 }}>{listings.data.map(listing => <OwnerCard key={listing._id} listing={listing} glowing={glowing.has(listing._id)} review={review.mutate} />)}</div> : <Empty />}</>}
    {tab === 'requests' && (sent.isLoading ? <SkeletonGrid /> : sent.data?.length ? <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(290px, 1fr))', gap: 18 }}>{sent.data.map(item => <SentCard key={item.request.request_id} item={item} glowing={glowing.has(item.request.request_id)} />)}</div> : <Empty />)}
    <RequestModal listing={requesting} form={requestForm} setForm={setRequestForm} onClose={() => setRequesting(null)} onSubmit={submitRequest} pending={sendRequest.isPending} />
    <ListingModal open={addOpen} form={listingForm} setForm={setListingForm} onClose={() => setAddOpen(false)} onSubmit={submitListing} pending={add.isPending} />
  </main></PageTransition>
}

const ListingGrid = ({ loading, listings, requestedIds, onRequest }: { loading: boolean; listings?: EquipmentListing[]; requestedIds: Set<string>; onRequest: (listing: EquipmentListing) => void }) => loading ? <SkeletonGrid /> : listings?.length ? <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(270px, 1fr))', gap: 18 }}>{listings.map(listing => { const requested = requestedIds.has(listing._id); return <article className="card card-hover" key={listing._id} style={{ padding: 20 }}><span className={`badge ${requested ? 'badge-amber' : 'badge-green'}`}>{requested ? 'Requested — Awaiting response' : 'Available'}</span><h3>{listing.equipment_name}</h3><p>{listing.description}</p><small><MapPin size={14} /> {listing.location} · <User size={14} /> {listing.owner_name}</small><button className="btn btn-primary" disabled={requested} style={{ width: '100%', marginTop: 16, opacity: requested ? .6 : 1 }} onClick={() => onRequest(listing)}>{requested ? 'Request sent' : 'Request to Borrow'}</button></article> })}</div> : <Empty />
const OwnerCard = ({ listing, glowing, review }: { listing: EquipmentListing; glowing: boolean; review: (input: { listingId: string; requestId: string; action: 'accept' | 'reject' }) => void }) => { const [open, setOpen] = useState(false); const pending = listing.requests.filter(r => r.status === 'pending'); return <motion.article animate={glowing ? { boxShadow: ['0 2px 16px rgba(27,94,32,.08)', '0 0 0 5px rgba(67,160,71,.35)', '0 2px 16px rgba(27,94,32,.08)'] } : {}} className="card" style={{ padding: 20 }}><span className={`badge ${statusStyle(listing.availability_status)}`}>{listing.availability_status}</span><h3>{listing.equipment_name}</h3><p style={{ color: 'var(--color-text-secondary)' }}>{listing.location}</p><button className="btn btn-secondary" onClick={() => setOpen(!open)} style={{ width: '100%' }}>Requests ({pending.length})</button><AnimatePresence>{open && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} style={{ overflow: 'hidden' }}>{listing.requests.map(request => <div key={request.request_id} style={{ marginTop: 12, padding: 12, borderRadius: 10, background: request.status === 'rejected' ? '#F5F5F5' : request.status === 'accepted' ? '#E8F5E9' : '#FFF8E1', opacity: request.status === 'rejected' ? .7 : 1 }}><strong>{request.requester_name}</strong> <span className={`badge ${statusStyle(request.status)}`}>{request.status}</span><div style={{ fontSize: 13, marginTop: 5 }}>{request.requester_address}<br /><Phone size={13} /> {request.requester_contact_number}<br />{request.message && `“${request.message}”`}<br /><small>{ago(request.requested_at)}</small></div>{request.status === 'pending' && <div style={{ display: 'flex', gap: 8, marginTop: 9 }}><button className="btn btn-primary" onClick={() => review({ listingId: listing._id, requestId: request.request_id, action: 'accept' })}><Check size={14} /> Accept</button><button className="btn btn-secondary" onClick={() => review({ listingId: listing._id, requestId: request.request_id, action: 'reject' })}>Reject</button></div>}</div>)}</motion.div>}</AnimatePresence></motion.article> }
const SentCard = ({ item, glowing }: { item: SentEquipmentRequest; glowing: boolean }) => <motion.article animate={glowing ? { scale: [1, 1.02, 1] } : {}} className="card" style={{ padding: 20 }}><span className={`badge ${statusStyle(item.request.status)}`}>{item.request.status}</span><h3>{item.listing.equipment_name}</h3><p>Owner: {item.listing.owner_name}</p>{item.request.status === 'accepted' && <div style={{ padding: 10, background: '#E8F5E9', borderRadius: 9 }}><Phone size={15} /> {item.listing.contact_number}</div>}<small>Requested {ago(item.request.requested_at)}</small></motion.article>
const Empty = () => <div className="card" style={{ padding: 52, textAlign: 'center', color: 'var(--color-text-secondary)' }}><PackageOpen size={42} /><p>No equipment requests to show yet.</p></div>
const RequestModal = ({ listing, form, setForm, onClose, onSubmit, pending }: { listing: EquipmentListing | null; form: RequestPayload; setForm: React.Dispatch<React.SetStateAction<RequestPayload>>; onClose: () => void; onSubmit: (event: FormEvent) => void; pending: boolean }) => <Modal open={!!listing} title={`Request ${listing?.equipment_name || ''}`} onClose={onClose}><form onSubmit={onSubmit}>{(['requester_name', 'requester_address', 'requester_contact_number'] as const).map(key => <label key={key} style={{ display: 'block', marginBottom: 12 }}>{key.replace(/_/g, ' ')}<input className="form-input" value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<label>Message (optional)<textarea className="form-input" rows={3} value={form.message || ''} onChange={e => setForm({ ...form, message: e.target.value })} /></label><button className="btn btn-primary" style={{ width: '100%', marginTop: 18 }} disabled={pending}><Send size={15} /> Send Request</button></form></Modal>
const ListingModal = ({ open, form, setForm, onClose, onSubmit, pending }: { open: boolean; form: { equipment_name: string; equipment_type: EquipmentType; description: string; location: string; contact_number: string }; setForm: React.Dispatch<React.SetStateAction<{ equipment_name: string; equipment_type: EquipmentType; description: string; location: string; contact_number: string }>>; onClose: () => void; onSubmit: (event: FormEvent) => void; pending: boolean }) => <Modal open={open} title="Add New Listing" onClose={onClose}><form onSubmit={onSubmit}>{(['equipment_name', 'description', 'location', 'contact_number'] as const).map(key => <label key={key} style={{ display: 'block', marginBottom: 12 }}>{key.replace(/_/g, ' ')}{key === 'description' ? <textarea className="form-input" rows={3} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /> : <input className="form-input" value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} />}</label>)}<label>equipment type<select className="form-select" value={form.equipment_type} onChange={e => setForm({ ...form, equipment_type: e.target.value as EquipmentType })}>{types.map(type => <option key={type}>{type}</option>)}</select></label><button className="btn btn-primary" style={{ width: '100%', marginTop: 18 }} disabled={pending}>Create Listing</button></form></Modal>
const Modal = ({ open, title, children, onClose }: { open: boolean; title: string; children: React.ReactNode; onClose: () => void }) => <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} style={{ position: 'fixed', inset: 0, zIndex: 500, display: 'grid', placeItems: 'center', padding: 16, background: 'rgba(0,0,0,.45)' }}><motion.div initial={{ y: 18 }} animate={{ y: 0 }} exit={{ y: 18 }} onClick={event => event.stopPropagation()} className="card" style={{ width: 'min(500px,100%)', padding: 24 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h2 style={{ marginTop: 0 }}>{title}</h2><button type="button" onClick={onClose} style={{ border: 0, background: 'none' }}><X /></button></div>{children}</motion.div></motion.div>}</AnimatePresence>
